name: Build Wasm component from Rust and push to OCI registry

on: 
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
     - uses: actions/checkout@v4
     
     - name: Setup wash CLI
       uses: cosmonic-labs/setup-wash-action@main
       with:
         wash-version: latest

     - name: Install wasm32-wasip2 target for Rust
       run: |
          rustup target add wasm32-wasip2

     - name: Checkout repository
       uses: actions/checkout@v4
       with:
        repository: ${{ github.repository_owner }}/${{ github.event.repository.name }}
        token: ${{ secrets.GITHUB_TOKEN }}

     - name: Fetch repository content
       run: |
          git fetch origin
          git checkout main

     - name: Compile Wasm binary
       run: |
          wash build

     - name: Get Wasm binary filename
       run: |
          WASM_FILENAME="$(basename ./target/wasm32-wasip2/debug/*.wasm .wasm)"
          echo "GITHUB_WASM_FILENAME=${WASM_FILENAME}" >>${GITHUB_ENV}

     - name: Login to GHCR
       uses: docker/login-action@v3
       with:
         registry: ghcr.io
         username: ${{ github.repository_owner }}
         password: ${{ secrets.GITHUB_TOKEN }}

     - name: Lowercase the organization name for ghcr.io
       run: |
          echo "GHCR_REPO_NAMESPACE=${GITHUB_REPOSITORY_OWNER,,}" >>${GITHUB_ENV}

     - name: Lowercase the repository name
       run: |
          REPO_NAME=${{ github.event.repository.name }}
          echo "GHCR_REPO_NAME=${REPO_NAME,,}" >>${GITHUB_ENV}

     - name: Push Wasm component to ghcr.io
       working-directory: ./target/wasm32-wasip2/debug/
       run: |
          wash oci push ghcr.io/${{ env.GHCR_REPO_NAMESPACE }}/components/${{ env.GHCR_REPO_NAME }}:${{ github.ref_name }} ./${{ env.GITHUB_WASM_FILENAME }}.wasm

     - name: Update image tag in Kubernetes manifest
       run: |
          DEPLOYMENT_FILE="manifests/component.yaml"
          OLD_IMAGE=$(grep "image:" "$DEPLOYMENT_FILE" | awk '{print $2}')
          NEW_IMAGE="ghcr.io/${{ env.GHCR_REPO_NAMESPACE }}/components/${{ env.GHCR_REPO_NAME }}:${{ github.ref_name }}"

          # Update the image tag
          sed -i "s|image:.*|image: $NEW_IMAGE|" "$DEPLOYMENT_FILE"

     - name: Commit manifest update
       run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add manifests/component.yaml
          git commit -m "Update image tag in manifest: $OLD_IMAGE -> $NEW_IMAGE"
          git push